export default {
  toggle: true,
  tabindex: false,
  addbuttons: false,
  maintain_context: false,
  cancellation_shortcut: false,
  brokerage_header: false,
  region_warning: true,
  save: { ctrl: true, alt: false, shift: false, key: "s", code: "KeyS" },
  print: { ctrl: true, alt: false, shift: false, key: "q", code: "KeyQ" },
  search: { ctrl: true, alt: false, shift: true, key: "F", code: "KeyF" },
  expand: { ctrl: true, alt: false, shift: false, key: "]", code: "BracketRight" },
  collapse: { ctrl: true, alt: false, shift: false, key: "[", code: "BracketLeft" },
  goto_listings: { ctrl: false, alt: false, shift: false, key: "F1", code: "F1" },
  toggle_privacy: { ctrl: false, alt: false, shift: false, key: "F2", code: "F2" },
  close_tab: { ctrl: false, alt: true, shift: false, key: "`", code: "Backquote" },
  exp_calc: { ctrl: false, alt: false, shift: false, key: "F3", code: "F3" },
  goto_assume: { ctrl: false, alt: false, shift: false, key: "F4", code: "F4" },
};
