name: Create Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
      - run: npm i -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: ParagonExtension_${{ github.ref_name }}.zip
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body_path: release.md
          files: ParagonExtension_${{ github.ref_name }}.zip
